version: "3.7"

services:
  terraform:
    image: hashicorp/terraform:0.12.29
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  kubectl:
    image: abdennour/kubectl:v1.16.2-aws1.16.281
    volumes:
      - .:/code
      - aws-creds:/root/.aws:ro
    entrypoint: kubectl
    environment:
      KUBECONFIG: /code/kubeconfig_awesome
      EKS_AWS_PROFILE: default
    ports:
     - 8090:8090

  aws:
    image: abdennour/aws
    restart: "no"
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    working_dir: /code

  helm:
    image: abdennour/helm:3.1.2-aws1.18.31-kubectlv1.17.4
    working_dir: /code
    volumes:
    - .:/code
    - helm-config:/root/.config/helm
    - helm-cache:/root/.cache/helm
    - aws-creds:/root/.aws:ro
    env_file:
      - .env
    environment:
      KUBECONFIG: /code/kubeconfig_awesome

  helmfile:
    image: abdennour/helmfile:v0.125.0-aws-1.18.105
    working_dir: /code
    volumes:
    - .:/code
    - helm-config:/root/.config/helm
    - helm-cache:/root/.cache/helm
    - aws-creds:/root/.aws:ro
    environment:
      KUBECONFIG: /code/kubeconfig_awesome

volumes:
  aws-creds:
    name: aws-creds
  helm-config:
  helm-cache:

